### ISSUE TITLE
Send StoryBoard photos to group.

### ISSUE THREAD

**Issue by DarleenF** [ekegulskiy/Woozie#2]

**Comment by DarleenF** [comment]
![screen 2](https://user-images.githubusercontent.com/32684199/35595925-2220f92a-05cd-11e8-959b-0691581a98ce.jpg)
![screen 3](https://user-images.githubusercontent.com/32684199/35595933-240bfcf8-05cd-11e8-9fb6-c3cc7b9b6d7f.jpg)
![screen 1](https://user-images.githubusercontent.com/32684199/35595893-0e19f29c-05cd-11e8-8733-d5afff739b0a.jpg)
![screen 4](https://user-images.githubusercontent.com/32684199/35595894-0e3bdb46-05cd-11e8-8a53-20f45d60a127.jpg)
![screen 5](https://user-images.githubusercontent.com/32684199/35595895-0e52c356-05cd-11e8-9b74-97a5503d2c54.jpg)

**Comment by ekegulskiy** [comment]
This issue was moved to kimmiet/Woozie#2
