### ISSUE TITLE
Kimmie Research APIs (Application Program Interface) such as Google for Voice Recognition

### ISSUE THREAD

**Issue by DarleenF** [ekegulskiy/Woozie#4]
See in which form the API gives you results & if it can be applied to what we need.

**Comment by kimmiet** [comment]
1. The output of the Google API is Speech to text and the main problem is it autocorrects. https://cloud.google.com/speech/
2. USC created a drunk speech detector: https://news.usc.edu/28961/The-Computer-Says-He-Sounds-Drunk/
3. And there is an algorithm created to detect drunk speech using python: https://arxiv.org/ftp/arxiv/papers/1610/1610.04426.pdf

**Comment by ekegulskiy** [comment]
Looks like we can use 'confidence' value from Google Speech API (see https://cloud.google.com/speech/reference/rest/v1/speech/recognize#SpeechRecognitionResult and example is here: https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/speech/cloud-client/src/main/java/com/example/speech/QuickstartSample.java )

**Comment by ekegulskiy** [comment]
This issue was moved to kimmiet/Woozie#4
