### ISSUE TITLE
Ezequiel Research to see if the gyroscope/accelerometer/camera.

### ISSUE THREAD

**Issue by DarleenF** [ekegulskiy/Woozie#9]
See if gyroscope/accelerometer/camera can be sued to implement these games:
1) 1 leg stand(30 secs without swaying)
2) Walk & turn (9 steps straight, then turn & walk 9 steps in other direction without stumbling)
3) Horizontal gauge nystagmus (eye tracking using camera)

**Comment by ekegulskiy** [comment]
Pedometer app or any other step counting examples can be used, i.e. http://www.gadgetsaint.com/android/create-pedometer-step-counter-android/#.WnoWX6inE2w

So will implement step counting as one of the measure factors for detecting level of intoxication.

**Comment by ekegulskiy** [comment]
There is an interesting eye tracking software in C++: https://github.com/elucideye/drishti

It may be significant effort to add to Android Java app, can take a look if time permits

**Comment by ekegulskiy** [comment]
This issue was moved to kimmiet/Woozie#9
